language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"

env:
  - DJANGO=https://www.djangoproject.com/download/1.5b1/tarball/
  - DJANGO=django==1.4.2 --use-mirrors
  - DJANGO=django==1.3.3 --use-mirrors

# command to install dependencies
install:
  - pip install $DJANGO
  - pip install -r .requirements.txt --use-mirrors
  - python setup.py develop

# command to run tests
script: python runtests.py

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=django==1.4.2 --use-mirrors
    - python: "3.2"
      env: DJANGO=django==1.3.3 --use-mirrors
